### ISSUE TITLE
Apply this template, migrate to GitHub actions

### ISSUE THREAD

**Issue by sbidoul** [shopinvader/shopinvader-addons-repo-template#1]
repo | 10.0 | 11.0 | 12.0 | 13.0 | 14.0
---- | ---- | ---- | ---- | ---- | ----
odoo-pim | ~https://github.com/shopinvader/odoo-pim/pull/72~ | N/A | ~https://github.com/shopinvader/odoo-pim/pull/71~  | ~https://github.com/shopinvader/odoo-pim/pull/73~  |  ~https://github.com/shopinvader/odoo-pim/pull/70~ (as part of the migration)
odoo-shopinvader | ~https://github.com/shopinvader/odoo-shopinvader/pull/922~ | N/A  |  ~https://github.com/shopinvader/odoo-shopinvader/pull/924~ |  ~https://github.com/shopinvader/odoo-shopinvader/pull/911~ |  ~https://github.com/shopinvader/odoo-shopinvader/pull/889~
odoo-shopinvader-payment | ~https://github.com/shopinvader/odoo-shopinvader-payment/pull/50~ | N/A  | ~https://github.com/shopinvader/odoo-shopinvader-payment/pull/51~ | ~https://github.com/shopinvader/odoo-shopinvader-payment/pull/47<br>https://github.com/shopinvader/odoo-shopinvader-payment/pull/48<br> https://github.com/shopinvader/odoo-shopinvader-payment/pull/49~ | ~https://github.com/shopinvader/odoo-shopinvader-payment/commit/b591709754e696ec59c90e10e2bf684e775334de~  |  
odoo-misc | ~https://github.com/shopinvader/odoo-misc/pull/12~ | N/A | ~https://github.com/shopinvader/odoo-misc/commit/8db2f559f2b29c939780b8118955b0175d49fa12<br>https://github.com/shopinvader/odoo-misc/commit/92060e081a4ac126e2bbffefb707ddc92599a2f6~ | ~https://github.com/shopinvader/odoo-misc/pull/11~ | N/A |

## procedure

- checkout a clean repo (`git clean -ffdx`)
- `copier git+https://github.com/shopinvader/shopinvader-addons-repo-template . `
- `pre-commit run -a oca-update-pre-commit-excluded-addons` (to avoid linting uninstallable files)
- `git add .`
- `git commit -m "Update dotfiles" --no-verify`
- `pre-commit run -a`
- `git add .`
- `git commit -m "Apply dotfiles" --no-verify`
- fix remaining lint issues in easy to review additional commits
- Check generated `requirements.txt` and update `test-requirements.txt`. Remove `--extra-index-url` if present in test requirements as it is [part of the GitHub action script](https://github.com/shopinvader/shopinvader-addons-repo-template/blob/961b10b4635a669d4e8d112b184963f8f07e88d6/.github/workflows/test.yml.jinja#L36).
- make PR
- :warning: visually check the action output (to make sure tests have actually been run, and detect false positives in case of bugs in the test scripts)

**Comment by simahawk** [comment]
Wondering: shouldn't be `PIP_INDEX_URL` [here](https://github.com/shopinvader/shopinvader-addons-repo-template/blob/master/.github/workflows/test.yml.jinja#L36) and use the new index as done on https://github.com/OCA/maintainer-quality-tools/pull/688

**Comment by sbidoul** [comment]
@simahawk The new OCA index is the one [used in the oca-ci image](https://github.com/sbidoul/oca-ci/blob/4a228a214ef1f63a8136c2ae413107746c34029c/Dockerfile#L121). Here we need the shopinvader wheels in addition to the OCA ones, hence the extra index. To do better we'll probably need a smarter index such as devpi or something ?

**Comment by sbidoul** [comment]
Before going further I would like to do the following test:
- merge the GitHub action on one repo/branch
- do or rebase a normal PR with failing tests to show the test failures are correctly detected
- try an ocabot merge on it to show the merge is rejected
- fix the PR and do an ocabot merge to show it works correctly

Who would like to test this ?

**Comment by PierrickBrun** [comment]
We could use this PR: https://github.com/shopinvader/odoo-shopinvader/pull/887 
EDIT: bad idea as it will merge it if the failing tests are not detected

**Comment by sbidoul** [comment]
@PierrickBrun we can do that:
- I merge https://github.com/shopinvader/odoo-shopinvader/pull/889
- you rebase https://github.com/shopinvader/odoo-shopinvader/pull/887, it should be red
- we try ocabot merge: it should be rejected and the probability it will pass is extremely low... and if it passes we revert
- you fix the PR and we ocabot merge it

**Comment by PierrickBrun** [comment]
Agreed.
FYI I may not be able to fix the PR quickly as I did not find what's wrong with it at the moment

**Comment by sbidoul** [comment]
Ok @PierrickBrun , let's do that. I merged. Please rebase shopinvader/odoo-shopinvader#887.

**Comment by PierrickBrun** [comment]
@sbidoul  Done

**Comment by sbidoul** [comment]
Voilà voilà, all done. Pfew.

Which other repo do we need to convert ? `pattern-import-export` I guess ?
So @sebastienbeau can stop the travis subscription and save the money for a big ~fiesta~ sprint.

**Comment by sebastienbeau** [comment]
> Voilà voilà, all done. Pfew.
> 
> Which other repo do we need to convert ? `pattern-import-export` I guess ?
> So @sebastienbeau can stop the travis subscription and save the money for a big ~fiesta~ sprint.

Yes, please do it. Thanks a lot for all of your work !

**Comment by sbidoul** [comment]
@sebastienbeau done.
